Adding api
mzlatic99/flutter-template pull request #2
Opened 2022-08-02 16:29 UTC by mzlatic99

Pozdrav @kdelivuk @lukacevica @PetricMatej , molim za feedback :)

2022-08-02 17:56 UTC, lukacevica requested changes

2022-08-02 17:56 UTC, lukacevica commented on lib/screens/home-screen/widgets/homes_guests_love.dart
> +              Text(
Please separate list title + view more button to new widget.

2022-08-02 17:56 UTC, lukacevica commented on lib/screens/home-screen/widgets/homes_guests_love.dart
> +                    isHorizontalList: true,
You can pass the whole accommodation object here.

2022-08-02 17:56 UTC, lukacevica commented on lib/screens/home-screen/widgets/popular_locations.dart
>                Text(
Here you can use newly created widget for list title and view more button.

2022-08-02 17:56 UTC, lukacevica commented on lib/screens/home-screen/widgets/popular_locations.dart
> +                  id: location.id,
You can pass the whole location object here.

2022-08-02 17:56 UTC, lukacevica commented on lib/screens/homes_guests_love-screen/homes_guests_love_screen.dart
> +                          isHorizontalList: false,
You can pass the whole accommodation object here.

2022-08-02 17:56 UTC, lukacevica commented on lib/screens/popular_locations_list-screen/popular_locations_list_screen.dart
> +                    id: location.id,
You can pass the whole location object here.

2022-08-02 17:56 UTC, lukacevica commented on lib/shared/homes_guests_love_card.dart
> +  // final String shortDescription;
Please delete unnecessary comments.

2022-08-02 17:56 UTC, lukacevica commented on lib/shared/homes_guests_love_card.dart
> +      starsRating.add(Icon(
You can separate this to new widget. Widget that will return list of stars depending on categorization.

2022-08-02 17:56 UTC, lukacevica commented on lib/screens/accommodation_details-screen/accommodation_details_screen.dart
> +              for (int i = 0; i < 4; i++) {
You can separate this to new widget. Widget that will return list of stars depending on categorization.

2022-08-03 11:02 UTC, mzlatic99 commented
Hi @lukacevica, I'm asking for feedback on new changes :)

2022-08-03 11:51 UTC, lukacevica commented
@mzlatic99  Nicely done! Your'e good to go and merge 😁

2022-08-03 11:51 UTC, lukacevica approved these changes

2022-08-03 15:53 UTC, mzlatic99 commented
Thank you😊

2022-08-03 15:53 UTC, merged